---
root: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
rules:
  comma-dangle:
    - error
    - only-multiline
  operator-linebreak:
    - error
    - before
  no-mixed-operators:
    - error
  semi:
    - error
    - never
  indent:
    - error
    - 2
